import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tako Project",
  description: "Generated by create next app",
  icons: {
    icon: "favicon.png",
  },
};

// Components
import { Navbar } from "@/components/Navbar/page";
import { Footer } from "@/components/Footer/page";

function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt-BR">
      <body className={`antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

export default RootLayout;
